---
- name: Gather facts
  ansible.builtin.setup:
    filter: ansible_os_family

- name: Update and upgrade packages on Alpine Linux
  block:
    - name: Update package index on Alpine Linux
      ansible.builtin.command: apk update

    - name: Upgrade all packages on Alpine Linux
      ansible.builtin.command: apk upgrade
  when: ansible_os_family == "Alpine"

- name: Update and upgrade packages on Debian-based systems
  block:
    - name: Update package index on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages on Debian-based systems
      ansible.builtin.apt:
        upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install common packages
  ansible.builtin.package:
    state: present
    name: "{{ common_packages }}"
