---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Update docker containers
  include_tasks: update.yml
  when: "{{ docker_check.rc == 0 }}"