---
- name: Install zsh
  ansible.builtin.package:
    state: present
    name: zsh

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh plugins
  block:
    - name: Install zsh plugins
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: 1
      loop: "{{ zsh_plugins }}"
      loop_control:
        label: "{{ item.repo }}"

- name: Install Powerline10k theme
  ansible.builtin.git:
    repo: "{{ powerlevel10k_repo }}"
    dest: "{{ powerlevel10k_dest }}"
    depth: 1

- name: Copy configuration files
  block:
    - name: Download and install config files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop: "{{ config_files }}"
      loop_control:
        label: "{{ item.url }}"

- name: Change user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh