---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Ensure Docker is installed
  fail:
    msg: "Docker is not installed on this host."
  when: docker_check.rc != 0

- name: Create Docker configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  when: docker_check.rc == 0

- name: Backup existing daemon.json if it exists
  stat:
    path: /etc/docker/daemon.json
  register: ansible_stat

- name: Backup existing daemon.json if it exists
  copy:
    src: /etc/docker/daemon.json
    dest: /etc/docker/daemon.json.bak
    remote_src: yes
  when: docker_check.rc == 0 and ansible_stat.stat.exists
  ignore_errors: yes

- name: Create/Update Docker daemon.json for TCP
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: docker_check.rc == 0
#
#- name: Restart Docker
#  service:
#    name: docker
#    state: restarted
#  when: docker_check.rc == 0
