---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Set fact if Docker is installed
  set_fact:
    is_docker_installed: "{{ docker_check.rc == 0 }}"

- name: Include daemon.json tasks
  include_tasks: configuration.yml
  when: is_docker_installed
