---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Ensure Docker is installed
  fail:
    msg: "Docker is not installed on this host."
  when: docker_check.rc != 0

- name: Create Docker configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
  when: docker_check.rc == 0

- name: Check if daemon.json exists
  stat:
    path: /etc/docker/daemon.json
  register: daemon_json_stat

- name: Generate new daemon.json to temporary location
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json.temp

- name: Compare current and new daemon.json
  command: diff /etc/docker/daemon.json /etc/docker/daemon.json.temp
  register: daemon_json_diff
  ignore_errors: yes
  when: daemon_json_stat.stat.exists

- name: Set fact for configuration changed
  set_fact:
    config_changed: "{{ daemon_json_diff.changed | default(true) }}"
  when: daemon_json_stat.stat.exists

- name: Set fact for configuration not existing
  set_fact:
    config_changed: true
  when: not daemon_json_stat.stat.exists

- block:
    - name: Backup existing daemon.json
      copy:
        src: /etc/docker/daemon.json
        dest: /etc/docker/daemon.json.bak
        remote_src: yes
      when: daemon_json_stat.stat.exists
      ignore_errors: yes

    - name: Apply new daemon.json
      copy:
        src: /etc/docker/daemon.json.temp
        dest: /etc/docker/daemon.json

    - name: Restart Docker
      service:
        name: docker
        state: restarted
      when: restart_docker | default(false)

  when: config_changed | bool