---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Include docker configuration tasks
  include_tasks: configuration.yml
  when: "{{ docker_check.rc == 0 }}"
