- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - zsh

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - repo: https://github.com/zsh-users/zsh-completions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
      dest: ~/.oh-my-zsh/custom/plugins/autoupdate

- name: Install Powerline10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Copy configs
  ansible.builtin.get_url:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - url: https://raw.githubusercontent.com/nstwfdev/configs/main/omz/.p10k.zsh
      dest: ~/.p10k.zsh
    - url: https://raw.githubusercontent.com/nstwfdev/configs/main/omz/.zshrc
      dest: ~/.zshrc

- name: Change user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh